.code
extern mProcs:QWORD
HidD_FlushQueue_wrapper proc
	jmp mProcs[0*8]
HidD_FlushQueue_wrapper endp
HidD_FreePreparsedData_wrapper proc
	jmp mProcs[1*8]
HidD_FreePreparsedData_wrapper endp
HidD_GetAttributes_wrapper proc
	jmp mProcs[2*8]
HidD_GetAttributes_wrapper endp
HidD_GetConfiguration_wrapper proc
	jmp mProcs[3*8]
HidD_GetConfiguration_wrapper endp
HidD_GetFeature_wrapper proc
	jmp mProcs[4*8]
HidD_GetFeature_wrapper endp
HidD_GetHidGuid_wrapper proc
	jmp mProcs[5*8]
HidD_GetHidGuid_wrapper endp
HidD_GetIndexedString_wrapper proc
	jmp mProcs[6*8]
HidD_GetIndexedString_wrapper endp
HidD_GetInputReport_wrapper proc
	jmp mProcs[7*8]
HidD_GetInputReport_wrapper endp
HidD_GetManufacturerString_wrapper proc
	jmp mProcs[8*8]
HidD_GetManufacturerString_wrapper endp
HidD_GetMsGenreDescriptor_wrapper proc
	jmp mProcs[9*8]
HidD_GetMsGenreDescriptor_wrapper endp
HidD_GetNumInputBuffers_wrapper proc
	jmp mProcs[10*8]
HidD_GetNumInputBuffers_wrapper endp
HidD_GetPhysicalDescriptor_wrapper proc
	jmp mProcs[11*8]
HidD_GetPhysicalDescriptor_wrapper endp
HidD_GetPreparsedData_wrapper proc
	jmp mProcs[12*8]
HidD_GetPreparsedData_wrapper endp
HidD_GetProductString_wrapper proc
	jmp mProcs[13*8]
HidD_GetProductString_wrapper endp
HidD_GetSerialNumberString_wrapper proc
	jmp mProcs[14*8]
HidD_GetSerialNumberString_wrapper endp
HidD_Hello_wrapper proc
	jmp mProcs[15*8]
HidD_Hello_wrapper endp
HidD_SetConfiguration_wrapper proc
	jmp mProcs[16*8]
HidD_SetConfiguration_wrapper endp
HidD_SetFeature_wrapper proc
	jmp mProcs[17*8]
HidD_SetFeature_wrapper endp
HidD_SetNumInputBuffers_wrapper proc
	jmp mProcs[18*8]
HidD_SetNumInputBuffers_wrapper endp
HidD_SetOutputReport_wrapper proc
	jmp mProcs[19*8]
HidD_SetOutputReport_wrapper endp
HidP_GetButtonCaps_wrapper proc
	jmp mProcs[20*8]
HidP_GetButtonCaps_wrapper endp
HidP_GetCaps_wrapper proc
	jmp mProcs[21*8]
HidP_GetCaps_wrapper endp
HidP_GetData_wrapper proc
	jmp mProcs[22*8]
HidP_GetData_wrapper endp
HidP_GetExtendedAttributes_wrapper proc
	jmp mProcs[23*8]
HidP_GetExtendedAttributes_wrapper endp
HidP_GetLinkCollectionNodes_wrapper proc
	jmp mProcs[24*8]
HidP_GetLinkCollectionNodes_wrapper endp
HidP_GetScaledUsageValue_wrapper proc
	jmp mProcs[25*8]
HidP_GetScaledUsageValue_wrapper endp
HidP_GetSpecificButtonCaps_wrapper proc
	jmp mProcs[26*8]
HidP_GetSpecificButtonCaps_wrapper endp
HidP_GetSpecificValueCaps_wrapper proc
	jmp mProcs[27*8]
HidP_GetSpecificValueCaps_wrapper endp
HidP_GetUsageValue_wrapper proc
	jmp mProcs[28*8]
HidP_GetUsageValue_wrapper endp
HidP_GetUsageValueArray_wrapper proc
	jmp mProcs[29*8]
HidP_GetUsageValueArray_wrapper endp
HidP_GetUsages_wrapper proc
	jmp mProcs[30*8]
HidP_GetUsages_wrapper endp
HidP_GetUsagesEx_wrapper proc
	jmp mProcs[31*8]
HidP_GetUsagesEx_wrapper endp
HidP_GetValueCaps_wrapper proc
	jmp mProcs[32*8]
HidP_GetValueCaps_wrapper endp
HidP_InitializeReportForID_wrapper proc
	jmp mProcs[33*8]
HidP_InitializeReportForID_wrapper endp
HidP_MaxDataListLength_wrapper proc
	jmp mProcs[34*8]
HidP_MaxDataListLength_wrapper endp
HidP_MaxUsageListLength_wrapper proc
	jmp mProcs[35*8]
HidP_MaxUsageListLength_wrapper endp
HidP_SetData_wrapper proc
	jmp mProcs[36*8]
HidP_SetData_wrapper endp
HidP_SetScaledUsageValue_wrapper proc
	jmp mProcs[37*8]
HidP_SetScaledUsageValue_wrapper endp
HidP_SetUsageValue_wrapper proc
	jmp mProcs[38*8]
HidP_SetUsageValue_wrapper endp
HidP_SetUsageValueArray_wrapper proc
	jmp mProcs[39*8]
HidP_SetUsageValueArray_wrapper endp
HidP_SetUsages_wrapper proc
	jmp mProcs[40*8]
HidP_SetUsages_wrapper endp
HidP_TranslateUsagesToI8042ScanCodes_wrapper proc
	jmp mProcs[41*8]
HidP_TranslateUsagesToI8042ScanCodes_wrapper endp
HidP_UnsetUsages_wrapper proc
	jmp mProcs[42*8]
HidP_UnsetUsages_wrapper endp
HidP_UsageListDifference_wrapper proc
	jmp mProcs[43*8]
HidP_UsageListDifference_wrapper endp
end
